"""Add optional requests

Revision ID: 248aae6d2dff
Revises: 3fc0a44b33ed
Create Date: 2026-10-03 12:46:17.686869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '248aae6d2dff'
down_revision = '3fc0a44b33ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('special_requests', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_column('special_requests')

    # ### end Alembic commands ###
