"""update booking schema

Revision ID: 3fc0a44b33ed
Revises: af37cca0ffae
Create Date: 2026-10-03 12:14:43.142586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fc0a44b33ed'
down_revision = 'af37cca0ffae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_name', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=False))
        batch_op.drop_column('guests')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('guests', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_column('phone')
        batch_op.drop_column('customer_name')

    # ### end Alembic commands ###
