"""add room description

Revision ID: 4647417618f9
Revises: 248aae6d2dff
Create Date: 2026-10-04 01:43:53.356795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4647417618f9'
down_revision = '248aae6d2dff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_bookings_room_id_rooms'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_bookings_room_id_rooms'), 'rooms', ['room_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_bookings_room_id_rooms'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_bookings_room_id_rooms'), 'rooms', ['room_id'], ['id'])

    # ### end Alembic commands ###
