"""update database schema

Revision ID: 7fe1919e27cb
Revises: ab2903904e59
Create Date: 2026-09-28 20:08:19.160979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fe1919e27cb'
down_revision = 'ab2903904e59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('guests', sa.Integer(), nullable=False),
    sa.Column('check_in', sa.Date(), nullable=False),
    sa.Column('check_out', sa.Date(), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.CheckConstraint("status IN ('pending', 'confirmed', 'cancelled', 'completed')", name=op.f('ck_bookings_booking_status_valid')),
    sa.CheckConstraint('check_out > check_in', name=op.f('ck_bookings_checkout_after_checkin')),
    sa.CheckConstraint('guests > 0', name=op.f('ck_bookings_guests_positive')),
    sa.CheckConstraint('total_price > 0', name=op.f('ck_bookings_total_price_positive')),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], name=op.f('fk_bookings_room_id_rooms')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_bookings_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bookings'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bookings')
    # ### end Alembic commands ###
