"""initial migration

Revision ID: ab2903904e59
Revises: 
Create Date: 2026-09-22 15:31:49.290738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab2903904e59'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('total_units', sa.Integer(), nullable=False),
    sa.Column('price_per_night', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='active', nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.CheckConstraint("status IN ('active', 'maintenance', 'inactive')", name=op.f('ck_rooms_status_valid')),
    sa.CheckConstraint('capacity > 0', name=op.f('ck_rooms_capacity_positive')),
    sa.CheckConstraint('price_per_night > 0', name=op.f('ck_rooms_price_positive')),
    sa.CheckConstraint('total_units > 0', name=op.f('ck_rooms_total_units_positive')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rooms')),
    sa.UniqueConstraint('name', name=op.f('uq_rooms_name'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), server_default='customer', nullable=False),
    sa.Column('email_verified', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('verification_token', sa.String(length=64), nullable=True),
    sa.Column('verification_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("role IN ('admin', 'customer')", name=op.f('ck_users_role_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username')),
    sa.UniqueConstraint('verification_token', name=op.f('uq_users_verification_token'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('rooms')
    # ### end Alembic commands ###
